spring:
  application:
    name: tarasov
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
reports:
  file:
    path: "test_report.json"
schedule:
  time: 300000

jwt:
  secret:
    key: secret
  access_token:
    time: 300
  refresh_token:
    time: 1500
